### ISSUE TITLE
ValueError: high is out of bounds for int32 

### ISSUE THREAD

**Issue by hmq2018** [danijar/portal#1]
First of all, thank you very much for developing this lib, it's really cool!

In my environment, the following code results in an error: "ValueError: high is out of bounds for int32." I believe this occurs because the maximum value for int32 is (2^{31} - 1) (which is (2,147,483,647)), and (2^{32}) exceeds this limit.

client.py
`identity = int(np.random.randint(2 ** 32))`

my environment:
Windows 10 22H2
Python 3.11 64Bit

**Comment by danijar** [comment]
Thanks! This is obsolete with the recent update.
